name: Nightly build windows

on:
  workflow_dispatch:

jobs:
  desktop-main:
    strategy:
      matrix:
        settings:
          - host: windows-latest
            target: x86_64-pc-windows-msvc
            bundles: msi

    name: Desktop - Main ${{ matrix.settings.target }}
    runs-on: ${{ matrix.settings.host }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js, pnpm and dependencies
        uses: ./.github/actions/setup-pnpm

      - name: Setup System and Rust
        uses: ./.github/actions/setup-system
        with:
          targets: ${{ matrix.settings.target }}

      - name: Build
        run: |
          pnpm desktop build --ci -v --target ${{ matrix.settings.target }} --bundles ${{ matrix.settings.bundles }}

      - name: Publish Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Spacedrive-Windows-msi-${{ inputs.target }}-${{ env.GITHUB_SHA_SHORT }}
          path: target/
